<a href="https://colab.research.google.com/github/jajapuramshivasai/projects_24/blob/main/Q_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pennylane

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 30.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.5/15.5 MB 23.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 36.1 MB/s eta 0:00:00


In [2]:
import torch
from torch import nn

import torchvision

import pennylane as qml
from pennylane import numpy as np
from pennylane.templates import RandomLayers

from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

In [3]:
class QonvLayer(nn.Module):
    def __init__(self, stride=2, device="default.qubit", wires=4, circuit_layers=4, n_rotations=8, out_channels=4, seed=None):
        super(QonvLayer, self).__init__()

        # init device
        self.wires = wires
        self.dev = qml.device(device, wires=self.wires)

        self.stride = stride
        self.out_channels = min(out_channels, wires)

        if seed is None:
            seed = np.random.randint(low=0, high=10e6)

        print("Initializing Circuit with random seed", seed)

        # random circuits
        @qml.qnode(device=self.dev, interface="torch")
        def circuit(inputs, weights):
            n_inputs=4
            # Encoding of 4 classical input values
            for j in range(n_inputs):
                qml.RY(inputs[j], wires=j)
            # Random quantum circuit
            RandomLayers(weights, wires=list(range(self.wires)), seed=seed)

            # Measurement producing 4 classical output values
            return [qml.expval(qml.PauliZ(j)) for j in range(self.out_channels)]

        weight_shapes = {"weights": [circuit_layers, n_rotations]}
        self.circuit = qml.qnn.TorchLayer(circuit, weight_shapes=weight_shapes)


    def draw(self):
        # build circuit by sending dummy data through it
        _ = self.circuit(inputs=torch.from_numpy(np.zeros(4)))
        print(self.circuit.qnode.draw())
        self.circuit.zero_grad()


    def forward(self, img):
        bs, h, w, ch = img.size()
        if ch > 1:
            img = img.mean(axis=-1).reshape(bs, h, w, 1)

        kernel_size = 2
        h_out = (h-kernel_size) // self.stride + 1
        w_out = (w-kernel_size) // self.stride + 1


        out = torch.zeros((bs, h_out, w_out, self.out_channels))

        # Loop over the coordinates of the top-left pixel of 2X2 squares
        for b in range(bs):
            for j in range(0, h_out, self.stride):
                for k in range(0, w_out, self.stride):
                    # Process a squared 2x2 region of the image with a quantum circuit
                    q_results = self.circuit(
                        inputs=torch.Tensor([
                            img[b, j, k, 0],
                            img[b, j, k + 1, 0],
                            img[b, j + 1, k, 0],
                            img[b, j + 1, k + 1, 0]
                        ])
                    )
                    # Assign expectation values to different channels of the output pixel (j/2, k/2)
                    for c in range(self.out_channels):
                        out[b, j // kernel_size, k // kernel_size, c] = q_results[c]


        return out

In [5]:
# Test QonvLayer

qonv = QonvLayer(circuit_layers=1, n_rotations=8, out_channels=4, stride=2)
# qonv.draw()
x = torch.rand(size=(1,28,28,1))

# Check OonvLayer Output shape
qonv(x).shape

Initializing Circuit with random seed 62985


torch.Size([1, 14, 14, 4])

In [6]:
def transform(x):
    x = np.array(x)
    x = x/255.0

    return torch.from_numpy(x).float()

In [7]:
def train(model, train_loader, epochs=50):
    print("Starting Training for {} epochs".format(epochs))

    model.train()

    optimizer = torch.optim.Adam(params=model.parameters(), lr=0.01)
    criterion = torch.nn.CrossEntropyLoss()

    losses = np.array([])
    accs = np.array([])

    for epoch in range(epochs):
        for i, (x, y) in enumerate(train_loader):

            # prepare inputs and labels
            x = x.view(-1, 28, 28, 1)
            y = y.long()

            # reset optimizer
            optimizer.zero_grad()

            # engage
            y_pred = model(x)

            # error, gradients and optimization
            loss = criterion(y_pred, y)
            loss.backward()
            optimizer.step()

            # output
            acc = accuracy_score(y, y_pred.argmax(-1).numpy())

            accs = np.append(accs, acc)
            losses = np.append(losses, loss.item())

            print("Epoch:", epoch,
                  "\tStep:", i,
                  "\tAcc:", round(acc, 3),
                  "\tLoss:", round(loss.item(),3),
                  "\tMean Loss:", round(float(losses[-30:].mean()), 3),
                  "\tMean Acc:", round(float(accs[-30:].mean()), 3)
                 )

            print("---------------------------------------\n")


    return model, losses, accs

In [ ]:
if True :


    # prepare dataset
    train_set = torchvision.datasets.MNIST(root='./mnist', train=True, download=True, transform=transform)
    test_set = torchvision.datasets.MNIST(root='./mnist', train=False, download=True, transform=transform)

    train_loader = torch.utils.data.DataLoader(dataset=train_set, batch_size=4)


    """
    Model
{
    Quanvolutional_Layer((2x2))
    Flatten
    Linear(14x14x4, 10)

}
    """

    # build the model
    model = torch.nn.Sequential(
        QonvLayer(stride=2, circuit_layers=2, n_rotations=4, out_channels=4, seed=9321727),
        torch.nn.Flatten(),
        torch.nn.Linear(in_features=14*14*4, out_features=10)
    )

    # start training
    model, losses, accs = train(model, train_loader, epochs=1)


    # plot losses and accuracies
    fig, (ax1, ax2) = plt.subplots(1,2, figsize=(16, 4))
    ax1.plot(losses)
    ax1.set_title("Loss")
    ax1.set_xlabel("Steps")
    ax1.set_ylabel("Loss")

    ax2.plot(accs)
    ax2.set_title("Accuracy")
    ax2.set_xlabel("Steps")
    ax2.set_ylabel("Accuracy")

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9912422/9912422 [00:00<00:00, 75382775.21it/s]


Extracting ./mnist/MNIST/raw/train-images-idx3-ubyte.gz to ./mnist/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28881/28881 [00:00<00:00, 45420207.66it/s]


Extracting ./mnist/MNIST/raw/train-labels-idx1-ubyte.gz to ./mnist/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1648877/1648877 [00:00<00:00, 74197678.30it/s]


Extracting ./mnist/MNIST/raw/t10k-images-idx3-ubyte.gz to ./mnist/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4542/4542 [00:00<00:00, 7868867.73it/s]

Extracting ./mnist/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./mnist/MNIST/raw



Initializing Circuit with random seed 9321727
Starting Training for 1 epochs
Epoch: 0 	Step: 0 	Acc: 0.0 	Loss: 2.468 	Mean Loss: 2.468 	Mean Acc: 0.0

Gradients Layer 0:
tensor([[ 7.5295e-03, -1.1390e-01, -3.3999e-02, -1.0915e-02],
        [-1.4345e-03, -3.1791e-02,  5.5926e-03, -1.4214e-09]])
---------------------------------------

Epoch: 0 	Step: 1 	Acc: 0.0 	Loss: 3.088 	Mean Loss: 2.778 	Mean Acc: 0.0

Gradients Layer 0:
tensor([[ 7.3182e-04, -6.7010e-01, -1.2990e-01, -1.8246e-03],
        [ 5.0285e-02,  3.3031e-01,  1.6141e-01,  2.5845e-08]])
---------------------------------------

Epoch: 0 	Step: 2 	Acc: 0.25 	Loss: 1.943 	Mean Loss: 2.5 	Mean Acc: 0.083

Gradients Layer 0:
tensor([[-1.5545e-03, -8.8757e-02, -1.4605e-02,  2.7170e-03],
        [ 9.9652e-03,  7.2404e-02,  3.1641e-02,  6.3465e-10]])
---------------------------------------

Epoch: 0 	Step: 3 	Acc: 0.25 	Loss: 3.471 	Mean Loss: 2.742 	Mean Acc: 0.125

Gradients Layer 0:
tensor([[-1.2469e-02, -1.0853e+00, -2.0134e-0